"""
strategy_backtest_report.py
============================

Phase G. Runs `decision_engine.build_meeting_slate` across all three
aggression modes (conservative, balanced, aggressive), with and without
the all-up satellite, and writes a single Markdown report comparing
risk-adjusted return profiles.

Walk-forward split (`bankroll.walk_forward_splits`) flags configurations
that look great in-sample but degrade out-of-sample.

Output: reports/STRATEGY_BACKTEST.md
"""
from __future__ import annotations

import json
from dataclasses import asdict
from pathlib import Path
from statistics import mean

from bankroll import Bet, replay, walk_forward_splits, BankrollMetrics
from betting_strategy import load_blackbook, load_factor_tables
from decision_engine import (
    APRIL_DATES, build_meeting_slate, settle_slate,
)


REPORT = Path("reports") / "STRATEGY_BACKTEST.md"


def run_config(mode: str, *, bankroll: float, enable_allup: bool,
                bb: dict, factor_tbls: dict) -> tuple[list[Bet], list[dict]]:
    """Run one config across all April dates, compounding bankroll
    meeting-by-meeting. Returns the bet list and the per-day slates."""
    cur_br = bankroll
    bets: list[Bet] = []
    slates: list[dict] = []
    for d in APRIL_DATES:
        slate = build_meeting_slate(
            d, bankroll=cur_br, mode=mode, enable_allup=enable_allup,
            blackbook=bb, factor_tbls=factor_tbls,
        )
        slates.append(slate)
        day_bets = settle_slate(slate)
        bets.extend(day_bets)
        cur_br = max(0.0, cur_br + sum(b.payout - b.stake for b in day_bets))
    return bets, slates


def metrics_row(name: str, m: BankrollMetrics, n_meetings: int) -> str:
    return (
        f"| {name} | {m.n_bets} | {m.hit_rate:.1%} | "
        f"${m.total_stake:.0f} | ${m.total_payout:.0f} | "
        f"{m.total_roi:+.1%} | {m.geom_return_per_bet:+.2%} | "
        f"{m.sharpe_like:+.2f} | {m.sortino_like:+.2f} | "
        f"{m.max_drawdown_frac:.1%} | ${m.max_drawdown_hkd:.0f} | "
        f"{m.longest_underwater} |"
    )


def by_play_breakdown(bets: list[Bet]) -> dict[str, BankrollMetrics]:
    groups: dict[str, list[Bet]] = {}
    for b in bets:
        play = b.tag.split("/")[-1] if "/" in b.tag else b.tag
        groups.setdefault(play, []).append(b)
    out = {}
    for k, lst in groups.items():
        _, m = replay(lst, starting_bankroll=1000.0)
        out[k] = m
    return out


def walk_forward_robustness(mode: str, *, bankroll: float, bb: dict,
                              factor_tbls: dict) -> list[dict]:
    """Train/test split on April meetings. Each test window's metrics tell
    us whether the strategy holds up out-of-sample."""
    splits = walk_forward_splits(APRIL_DATES, n_splits=4, min_train=3)
    out = []
    for train, test in splits:
        cur = bankroll
        bets: list[Bet] = []
        for d in test:
            slate = build_meeting_slate(d, bankroll=cur, mode=mode,
                                          enable_allup=True,
                                          blackbook=bb, factor_tbls=factor_tbls)
            day_bets = settle_slate(slate)
            bets.extend(day_bets)
            cur = max(0.0, cur + sum(b.payout - b.stake for b in day_bets))
        _, m = replay(bets, starting_bankroll=bankroll)
        out.append({
            "train_window": f"{train[0]}..{train[-1]}",
            "test_window":  f"{test[0]}..{test[-1]}",
            "n_test_meets": len(test),
            "metrics": m,
        })
    return out


def main(bankroll: float = 1000.0):
    bb = load_blackbook()
    factor_tbls = load_factor_tables()

    sections: list[str] = []
    sections.append("# Strategy Backtest — April 2026")
    sections.append("")
    sections.append(f"_Generated by strategy_backtest_report.py_  ")
    sections.append(f"Starting bankroll: **${bankroll:.0f}**.  "
                    f"Meetings: {len(APRIL_DATES)} (Apr 1 – Apr 22 2026).  "
                    f"Compounding: bankroll rolls forward day-to-day.")
    sections.append("")

    # ------------------------------------------------------------------
    # 1. Mode comparison (with all-up + without)
    # ------------------------------------------------------------------
    sections.append("## 1. Mode comparison")
    sections.append("")
    sections.append("| Config | bets | hit | stake | payout | ROI | "
                    "geom/bet | Sharpe | Sortino | MDD% | MDD$ | UW |")
    sections.append("|---|---|---|---|---|---|---|---|---|---|---|---|")

    config_results = {}
    for mode in ("conservative", "balanced", "aggressive", "uncapped"):
        for allup in (False, True):
            tag = f"{mode}{' + allup' if allup else ''}"
            bets, slates = run_config(mode, bankroll=bankroll,
                                        enable_allup=allup,
                                        bb=bb, factor_tbls=factor_tbls)
            _, m = replay(bets, starting_bankroll=bankroll)
            sections.append(metrics_row(tag, m, len(APRIL_DATES)))
            config_results[tag] = (bets, m, slates)
    sections.append("")
    sections.append("> **Geom/bet** = compound-rate per bet; the metric "
                    "actually being optimised for long-term capital growth. "
                    "**Sharpe-like** uses log-returns of bankroll. **MDD** "
                    "is peak-to-trough decline. **UW** = longest underwater "
                    "stretch (bets between peak and recovery).")
    sections.append("")

    # ------------------------------------------------------------------
    # 2. Per-play (pool) breakdown for balanced mode
    # ------------------------------------------------------------------
    sections.append("## 2. Per-pool breakdown (balanced + allup)")
    sections.append("")
    sections.append("| Pool | bets | hit | stake | payout | ROI | "
                    "geom/bet | Sharpe | MDD% |")
    sections.append("|---|---|---|---|---|---|---|---|---|")
    bal_bets = config_results["balanced + allup"][0]
    by_pool = by_play_breakdown(bal_bets)
    for pool, m in sorted(by_pool.items(), key=lambda kv: -kv[1].total_roi):
        sections.append(
            f"| {pool} | {m.n_bets} | {m.hit_rate:.1%} | "
            f"${m.total_stake:.0f} | ${m.total_payout:.0f} | "
            f"{m.total_roi:+.1%} | {m.geom_return_per_bet:+.2%} | "
            f"{m.sharpe_like:+.2f} | {m.max_drawdown_frac:.1%} |"
        )
    sections.append("")

    # ------------------------------------------------------------------
    # 3. Walk-forward robustness check
    # ------------------------------------------------------------------
    sections.append("## 3. Walk-forward robustness (balanced mode)")
    sections.append("")
    sections.append("Each row tests a single forward window after training "
                    "on all prior meetings. Big positive ROIs that flip "
                    "negative in later windows = overfit.")
    sections.append("")
    sections.append("| Train window | Test window | bets | ROI | "
                    "geom/bet | Sharpe | MDD% |")
    sections.append("|---|---|---|---|---|---|---|")
    wf = walk_forward_robustness("balanced", bankroll=bankroll, bb=bb,
                                    factor_tbls=factor_tbls)
    for r in wf:
        m: BankrollMetrics = r["metrics"]
        sections.append(
            f"| {r['train_window']} | {r['test_window']} | {m.n_bets} | "
            f"{m.total_roi:+.1%} | {m.geom_return_per_bet:+.2%} | "
            f"{m.sharpe_like:+.2f} | {m.max_drawdown_frac:.1%} |"
        )
    sections.append("")

    # ------------------------------------------------------------------
    # 4. Insights
    # ------------------------------------------------------------------
    sections.append("## 4. Where the edge lives (and where it doesn't)")
    sections.append("")
    insights: list[str] = []
    bal_m: BankrollMetrics = config_results["balanced + allup"][1]
    cons_m = config_results["conservative + allup"][1]
    agg_m = config_results["aggressive + allup"][1]
    if bal_m.total_roi > cons_m.total_roi and bal_m.total_roi > agg_m.total_roi:
        insights.append("- **Balanced is the sweet spot.** Conservative is too "
                        "restrictive on a $1000 bankroll (rejects most "
                        "positive-edge bets via the 20% edge floor); "
                        "aggressive's lower edge floor admits too many "
                        "marginal-EV bets.")
    if cons_m.n_bets <= 3:
        insights.append(f"- **Conservative effectively doesn't bet** "
                        f"({cons_m.n_bets} bets across {len(APRIL_DATES)} "
                        f"meetings). At this bankroll, the 20% edge floor "
                        f"plus WIN/PLACE-only whitelist filters out "
                        f"essentially everything.")
    # Find best pool
    if by_pool:
        best_pool = max(by_pool.items(), key=lambda kv: kv[1].total_roi)
        worst_pool = min(by_pool.items(), key=lambda kv: kv[1].total_roi)
        insights.append(f"- **Best pool: `{best_pool[0]}`** "
                        f"(ROI {best_pool[1].total_roi:+.1%}, "
                        f"{best_pool[1].n_bets} bets).")
        insights.append(f"- **Worst pool: `{worst_pool[0]}`** "
                        f"(ROI {worst_pool[1].total_roi:+.1%}, "
                        f"{worst_pool[1].n_bets} bets) — candidate for "
                        f"removal from whitelist.")
    # Walk-forward variance
    test_rois = [r["metrics"].total_roi for r in wf]
    if len(test_rois) >= 2:
        if max(test_rois) > 0 and min(test_rois) < -0.2:
            insights.append("- **Walk-forward windows show strong sign-flips "
                            "in ROI** — the strategy's results are dominated "
                            "by sample variance, not stable edge. Treat any "
                            "headline ROI with skepticism until ≥30 settled "
                            "meetings.")

    insights.append("")
    insights.append("### Recommendations")
    insights.append("- Do NOT scale up stakes until ≥3 forward windows show "
                    "consistent positive Sharpe.")
    insights.append("- Bankroll discipline > bet selection at this sample "
                    "size: meeting cap of 15% is doing more work than the "
                    "edge model.")
    insights.append("- The all-up satellite **adds variance with little EV** "
                    "on April data — keep at ≤5% per chain or remove "
                    "entirely until per-leg p_used is calibrated against "
                    "results.")

    for line in insights:
        sections.append(line)
    sections.append("")

    REPORT.parent.mkdir(exist_ok=True)
    REPORT.write_text("\n".join(sections), encoding="utf-8")
    print(f"Wrote {REPORT}")

    # Also dump JSON for downstream tooling
    json_path = REPORT.with_suffix(".json")
    json_path.write_text(json.dumps({
        "bankroll": bankroll,
        "configs": {tag: asdict(m) for tag, (_, m, _) in config_results.items()},
        "by_pool": {k: asdict(v) for k, v in by_pool.items()},
        "walk_forward": [
            {"train": r["train_window"], "test": r["test_window"],
             "metrics": asdict(r["metrics"])}
            for r in wf
        ],
    }, indent=2, default=str), encoding="utf-8")
    print(f"Wrote {json_path}")


if __name__ == "__main__":
    import sys
    bk = float(sys.argv[1]) if len(sys.argv) > 1 else 1000.0
    main(bk)
